backend:
  name: git-gateway
  branch: main
  squash_merges: true

media_folder: source/images
public_folder: /images

publish_mode: editorial_workflow

collections:
  - name: post
    label: 文章
    folder: source/_posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: md
    editor:
      preview: false
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 日期, name: date, widget: datetime, format: YYYY-MM-DD HH:mm:ss }
      - { label: 分类, name: categories, widget: list, required: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 正文, name: body, widget: markdown }
